### ISSUE TITLE
M5Stack Ultrasonic I/O sensor - does work with longer timeout

### ISSUE THREAD

**Issue by Cenedd** [Chill-Division/M5Stack-ESPHome#10]
I fell into the same trap as you seem to have with the I/O version of this sensor.  Thought it was faulty until I found your comments that only the i2c version works (with modified code).  I couldn't work out why it should be different given their code was very similar:

```
    digitalWrite(_trig, LOW);
    delayMicroseconds(2);
    // Sets the trigPin on HIGH state for 10 micro seconds.
    // 将TrigPin设定为高电平状态，持续10微秒。

    digitalWrite(_trig, HIGH);
    delayMicroseconds(10);
    digitalWrite(_trig, LOW);

    // Reads the echoPin, returns the sound wave travel time in microseconds
    //读取echoPin，返回以微秒为单位的声波移动时间
    float duration = pulseIn(_echo, HIGH);

    return duration;
```

I managed to get a cheap oscilloscope on it and after much swearing (the software is awful) it looks like there's just a much longer delay (about 42ms) between the trigger pulse and the response pulse.  Note the timescale is in milliseconds, not microseconds!

![Ultrasonic-io-oscilloscope](https://github.com/user-attachments/assets/7c8fc00a-600d-4fa2-abfa-3f072092c31f)

Setting a longer timeout for the default ultrasonic component seems to compensate for this.  8m gives a limited max range or about 0.88m and the occasional complaint about the component blocking. 9 or 10m will allow longer range (at least 1.8m....I ran out of space) but will constantly complain about the component blocking.

```
sensor:
  - platform: ultrasonic
    trigger_pin: GPIO2
    echo_pin: GPIO1
    name: "Distance"
    id: fill_level
    update_interval: 1s
    timeout: 8m     #8m minimum
    unit_of_measurement: "m"
```

Hope that's of some use to someone.
Gareth
