### ISSUE TITLE
(Working Example) M5Stack OLED Unit 1.3" 128 × 64 Display (SH1107)

### ISSUE THREAD

**Issue by DavidGeorge528** [Chill-Division/M5Stack-ESPHome#13]
Here is a minimal example for running the M5 Stack OLED Unit 1.3" display

```yaml
i2c: 
  sda: 2
  scl: 1

font:
  - file: "gfonts://Roboto@medium"
    id: my_font
    size: 18
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/³µ'

display:
  - platform: ssd1306_i2c
    model: "SH1107 128x64"
    address: 0x3C
    update_interval: "30s"
    rotation: 90
    offset_y: 96
    lambda: |-
      it.printf(0, 0, id(my_font), "Hello");
      it.printf(0, 20, id(my_font), "World!");
```
![IMG_4064 2](https://github.com/user-attachments/assets/4740b21d-98d9-4b83-8930-d6177ffb27f3)

This example assumes the device is plugged into the Grove port on an M5 stack Atom or similar, I2C pins will likely differ for others.

Some caveats:
- The `offset_y` was necessary (on my board at least) as without it the screen would display some debug information or even just garbage that I couldn't write over (see below)
![IMG_4065](https://github.com/user-attachments/assets/97e75906-bec5-45ac-9c62-72bb736ea058)
- I get the following warning on each update, which I am not entirely sure how to fix or if its an issue at all
```
[13:26:33][W][component:237]: Component display took a long time for an operation (306 ms).
[13:26:33][W][component:238]: Components should block for at most 30 ms.
```
