### ISSUE TITLE
MLX90640 "The sensor is not connected"

### ISSUE THREAD

**Issue by zhudhjen** [Chill-Division/M5Stack-ESPHome#15]
Thanks for the guides provided!

First time working on esp32 and MLX90640. I just got an m5stack [T-Lite](https://docs.m5stack.com/en/app/T-Lite), which is essentially [m5stick c plus](https://docs.m5stack.com/en/core/m5stickc_plus) with a [hat thermal](https://docs.m5stack.com/en/hat/hat-thermal) attached. The connection is through pins instead of the grove connector, while the interface is supposed to be the same (I2C:0x33). I am trying to get it working on esphome instead of the stock firmware as the API frequently get unresponsive.

I've been following [your thermal camera guide](https://github.com/Chill-Division/M5Stack-ESPHome/blob/926ca7b10b82df20872bbf22a2cf2f8d11cd30bc/Thermal%20Camera%20Unit%20(MLX90640).md), combined with the [official esphome guide for m5stick c plus](https://devices.esphome.io/devices/M5Stack-M5StickC-PLUS). Attached the full config at the end.

Based on the doc of [the hat thermal](https://docs.m5stack.com/en/hat/hat-thermal), I am setting the `scl=26, sda=0, freq=400khz`

However, I am not able to get the sensor to work due to some error (in log): 
```
[MLX90640:206] | The sensor is not connected
```

What could potentially lead to this? Any help appreciated!

The full config:
```yaml
substitutions:
  devicename: pitayathermal
  upper_devicename: PITAYATHERMAL

esphome:
  name: $devicename
  platform: ESP32
  board: m5stick-c
  platformio_options:
    upload_speed: 115200
  libraries:
    - FS
    - Wire
    - SPIFFS

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: $devicename Fallback Hotspot
    password: !secret wifi_password

captive_portal:

logger:

# Enable Home Assistant API
api:
  encryption:
    key: **key**

ota:
  - platform: esphome
    password: **pw**

external_components:
  - source: github://martydingo/esphome-axp192
    components: axp192
  - source:
      type: git
      url: https://github.com/chill-Division/M5Stack-ESPHome/
      ref: main
    components: camera_mlx90640

# AXP192 power management - must be present to initialize TFT power on
sensor:
  - platform: axp192
    model: M5STICKC
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    battery_level:
      name: "PitayaThermal Battery Level"
      id: "pitayathermal_batterylevel"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: ${upper_devicename} Button A
    on_press:
      then:
        - light.turn_on: led1
    on_release:
      then:
        - light.turn_off: led1

  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${upper_devicename} Button B
    on_press:
      then:
        - light.turn_on: led1
    on_release:
      then:
        - light.turn_off: led1

light:
  - platform: monochromatic
    output:  builtin_led
    name: ${upper_devicename} Led
    id: led1

output:
  - platform: ledc
    pin: 10
    inverted: true
    id: builtin_led

remote_transmitter:
  - pin:
      number: GPIO9
    carrier_duty_percent: 50%

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

i2c:
   - id: bus_a
     sda: GPIO21
     scl: GPIO22
     scan: True

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 12

color:
  - id: my_black
    red: 100%
    green: 100%
    blue: 100%
  - id: my_white
    red: 0%
    green: 0%
    blue: 0%

# 1.14 inch, 135*240 Colorful TFT LCD, ST7789v2
display:
  - platform:  st7789v
    model: TTGO TDisplay 135x240
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 270
    lambda: |-
      it.fill(id(my_black));
      it.print(80, 0, id(roboto), id(my_white), TextAlign::TOP_CENTER, "M5Stick Test");

i2s_audio:
  id: bus_i2s
  i2s_lrclk_pin: G26
  i2s_bclk_pin: G0

microphone:
  - platform: i2s_audio
    i2s_din_pin: GPIO34
    i2s_audio_id: bus_i2s
    adc_type: external
    pdm: true
    id: mic

# This is neccessary to load the text_sensor library, can be left empty though
text_sensor:

# The Thermal Camera sensor itself
camera_mlx90640:
  id: thermal_cam
  update_interval: 5s
  sda: 0  # I2C SDA PIN
  scl: 26  # I2C SCL PIN
  frequency: 400000  # I2C Clock Frequency
  address: 0x33 # MLX90640 Address
  mintemp: 15 # Minimal temperature for color mapping
  maxtemp: 100 # Maximal temperature for color mapping
  refresh_rate: 0x04 # 0x05 For 16Hz or 0x04 for 8Hz
  min_temperature:
      name: "PitayaThermal Min temp"
  max_temperature:
      name: "PitayaThermal Max temp"
  mean_temperature:
      name: "PitayaThermal Mean temp"
  median_temperature:
      name: "PitayaThermal Median temp"

web_server:
  port: 80

```

**Comment by zhudhjen** [comment]
I noticed `i2s_audio` is using the same pins, could there be a conflict?

**Comment by ChillingSilence** [comment]
Yeah that code when my friend had it written was never designed to display images on a built-in screen, and I'd assume it wouldn't work.
It can probably be made to, with a lot of tender loving care, but it's unfortunately not something I'm capable of doing.

**Comment by zhudhjen** [comment]
I did not mean to display images on the built-in screen -- well, not yet. I just need the max temp sensor value for now. Those configs about display are actually unrelated (just to make sure the code deploys correctly). Removed them for a simplified version, and it still has the same error:

```yaml
substitutions:
  devicename: pitayathermal
  upper_devicename: PITAYATHERMAL

esphome:
  name: $devicename
  platform: ESP32
  board: m5stick-c
  platformio_options:
    upload_speed: 115200
  libraries:
    - FS
    - Wire
    - SPIFFS

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: $devicename Fallback Hotspot
    password: !secret wifi_password

captive_portal:

logger:

# Enable Home Assistant API
api:

ota:

external_components:
  - source: github://martydingo/esphome-axp192
    components: [axp192]
  - source:
      type: git
      url: https://github.com/chill-Division/M5Stack-ESPHome/
      ref: main
    components: camera_mlx90640

# AXP192 power management - must be present to initialize TFT power on
sensor:
  - platform: axp192
    model: M5STICKC
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    battery_level:
      name: "PitayaThermal Battery Level"
      id: "pitayathermal_batterylevel"

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

i2c:
   - id: bus_a
     sda: GPIO21
     scl: GPIO22
     scan: True
   - id: bus_b
     sda: GPIO0
     scl: GPIO26
     scan: True

# This is neccessary to load the text_sensor library, can be left empty though
text_sensor:

# The Thermal Camera sensor itself
camera_mlx90640:
  id: thermal_cam
  update_interval: 5s
  sda: 0  # I2C SDA PIN
  scl: 26  # I2C SCL PIN
  frequency: 400000  # I2C Clock Frequency
  address: 0x33 # MLX90640 Address
  mintemp: 15 # Minimal temperature for color mapping
  maxtemp: 100 # Maximal temperature for color mapping
  refresh_rate: 0x03 # 0x05 For 16Hz or 0x04 for 8Hz
  min_temperature:
      name: "PitayaThermal Min temp"
  max_temperature:
      name: "PitayaThermal Max temp"
  mean_temperature:
      name: "PitayaThermal Mean temp"
  median_temperature:
      name: "PitayaThermal Median temp"

web_server:
  port: 80

```

Additionally, I did I2C scans that was able to find the address as expected:

```
[02:56:19][C][i2c.arduino:071]: I2C Bus:
[02:56:19][C][i2c.arduino:072]:   SDA Pin: GPIO21
[02:56:19][C][i2c.arduino:073]:   SCL Pin: GPIO22
[02:56:19][C][i2c.arduino:074]:   Frequency: 50000 Hz
[02:56:19][C][i2c.arduino:086]:   Recovery: bus successfully recovered
[02:56:19][I][i2c.arduino:096]: Results from i2c bus scan:
[02:56:19][I][i2c.arduino:102]: Found i2c device at address 0x34
[02:56:19][I][i2c.arduino:102]: Found i2c device at address 0x51
[02:56:19][I][i2c.arduino:102]: Found i2c device at address 0x68
[02:56:19][C][i2c.arduino:071]: I2C Bus:
[02:56:19][C][i2c.arduino:072]:   SDA Pin: GPIO0
[02:56:19][C][i2c.arduino:073]:   SCL Pin: GPIO26
[02:56:19][C][i2c.arduino:074]:   Frequency: 50000 Hz
[02:56:19][C][i2c.arduino:086]:   Recovery: bus successfully recovered
[02:56:19][I][i2c.arduino:096]: Results from i2c bus scan:
[02:56:19][I][i2c.arduino:102]: Found i2c device at address 0x33
```

**Comment by zhudhjen** [comment]
Ok, I removed the power management I2C now and it works. Do you have any idea why this could block the thermal sensor?

Latest (simplest) yaml:
```yaml
substitutions:
  devicename: pitayathermal
  upper_devicename: PITAYATHERMAL

esphome:
  name: $devicename
  platform: ESP32
  board: m5stick-c
  platformio_options:
    upload_speed: 115200
  libraries:
    - FS
    - Wire
    - SPIFFS

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: $devicename Fallback Hotspot
    password: !secret wifi_password

captive_portal:

logger:

api:

ota:

external_components:
  - source:
      type: git
      url: https://github.com/chill-Division/M5Stack-ESPHome/
      ref: main
    components: camera_mlx90640

# This is neccessary to load the text_sensor library, can be left empty though
text_sensor:

# The Thermal Camera sensor itself
sensor:
camera_mlx90640:
  id: thermal_cam
  update_interval: 5s
  sda: 0  # I2C SDA PIN
  scl: 26  # I2C SCL PIN
  frequency: 400000  # I2C Clock Frequency
  address: 0x33 # MLX90640 Address
  mintemp: 15 # Minimal temperature for color mapping
  maxtemp: 100 # Maximal temperature for color mapping
  refresh_rate: 0x03 # 0x05 For 16Hz or 0x04 for 8Hz
  min_temperature:
      name: "PitayaThermal Min temp"
  max_temperature:
      name: "PitayaThermal Max temp"
  mean_temperature:
      name: "PitayaThermal Mean temp"
  median_temperature:
      name: "PitayaThermal Median temp"

web_server:
  port: 80

```
