### ISSUE TITLE
Did you get the nanoC6 working with i2c

### ISSUE THREAD

**Issue by jtenniswood** [Chill-Division/M5Stack-ESPHome#22]
Did you get the nanoC6 working with i2c? I can't get a config to work, it's driving me made!
Thanks

**Comment by ChillingSilence** [comment]
What's your yaml?
Make sure you have:
<pre>
sda: 2
scl: 1
</pre>

**Comment by ChillingSilence** [comment]
- Need to clarify: are you running ESPHome 2025.6.0? Or earlier?
- What yaml you're using
- What sensor components you've got

My crystal ball isn't working otherwise and one line of "it no worky" is hard to assist with a solution for.

**Comment by simenopsahl** [comment]
For what it's worth my NanoC6 i2c works with this

```yaml
i2c:
# Grove port
  - id: i2c_grove
    sda: GPIO2
    scl: GPIO1
    frequency: 50kHz
    scan: false # this might be needed
```
