### ISSUE TITLE
PBHub - Support for ADC

### ISSUE THREAD

**Issue by MRobi1** [Chill-Division/M5Stack-ESPHome#4]
Trying to run a pair of watering units off of a PB.Hub and would like to have the moisture values from the sensor.

When I set the pin to m5stack_pbhub it gives me an error of "[m5stack_pbhub] is an invalid option for [pin]."

```
sensor:
  - platform: adc
    pin:
      m5stack_pbhub: M5Stack_HUB
      # Use channel 0, pin number 0
      number: 01
      mode:
        input: true
```
Is this something that can be added in the m5stack_pbhub component to support adc?

**Comment by ChillingSilence** [comment]
It's my understanding that the firmware was only created with the intention of it being a switch / binary sensor. It'd need further development done to take ADC which I haven't got capacity to fund development for sorry. Somebody else may add it though

**Comment by regencape** [comment]
> Trying to run a pair of watering units off of a PB.Hub and would like to have the moisture values from the sensor.

This was exactly my plan. :) But somehow I run into an issue, not only with the sensors. ESPhome uploads the firmware without trouble, but there's an issue with the api. The api however seems to be configured just fine. When I run the firmware without the hub-part, the api gives no problem. I'm no expert, but tried to nail it down, and the problem appears when I introduce this part. I removed the sensor and switch part, for now.

```
 m5stack_pbhub:
   - id: 'M5Stack_HUB'
     address: 0x61
     sda: 16
     scl: 17
```

> INFO Starting log output from 192.168.xxx.xx using esphome API
> WARNING Can't connect to ESPHome API for xxx_some_name_xxx @ 192.168.xxx.xx: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.xxx.xx', port=6053))]: [Errno 111] Connect call failed ('192.168.xxx.xx', 6053) (SocketAPIError)

The original IP address is correct (otherwise the firmware wouldn't have updated anyhow). Any idea's? Are the pin numbers right? Can't find clear documentation (at least not clear to me) on the M5stack site to check these numbers. Help would be greatly appreciated.
